Refines "make safety" invocation
Bumping to latest version to debug problems with "ordinal not in range".
This version bump does not solve, but using the `--stdin` flag oddly
does. I cannot explain why `--stdin` with a bash redirect works, whereas
`-r` does not. In our other repositories, the `-r` option works fine.

The stack trace, for future reference, was:

  File "/home/conor/.virtualenvs/securedrop.org/local/lib/python2.7/site-packages/safety/formatter.py", line 115, in render
    table.append("│ {:76} │".format(line))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 22: ordinal not in range(128)
Makefile:90: recipe for target 'safety' failed
make: *** [safety] Error 1

Could not figure it out, and timebox was reached.