Installs dependencies for pshtt
Upgrades setuptools inside virtualenv
Toward installing `pshtt`: the pshtt dependency sslyze
requires a modern version of `setuptools`, otherwise:

    error in SSLyze setup command: Invalid environment marker:
    python_version < "3.5"

Sets locale to satisfy finicky pshtt installer, otherwise we get:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 23:
    ordinal not in range(128)

EVALUATE: don't double install libssl-dev

It's only needed in the temporary build container (I think).