Upgrades Molecule to v2.8.2
We don't use the `--upgrade` flag for `pip-compile`, so we were still
version-locking an old version of Molecule that did not work with
Ansible. CI failed with an error on the testinfra run:

    ==================================== ERRORS ====================================
    ___________________ ERROR collecting ci/tests/test_basic.py ____________________
    ../../../.venv/lib/python2.7/site-packages/testinfra/plugin.py:136: in pytest_generate_tests
        ansible_inventory=metafunc.config.option.ansible_inventory,
    ../../../.venv/lib/python2.7/site-packages/testinfra/host.py:125: in get_hosts
        for backend in testinfra.backend.get_backends(hosts, **kwargs):
    ../../../.venv/lib/python2.7/site-packages/testinfra/backend/__init__.py:84: in get_backends
        for name in klass.get_hosts(host, **kw):
    ../../../.venv/lib/python2.7/site-packages/testinfra/backend/ansible.py:72: in get_hosts
        return AnsibleRunner(kwargs.get("ansible_inventory")).get_hosts(host)
    ../../../.venv/lib/python2.7/site-packages/testinfra/utils/ansible_runner.py:150: in __init__
        self.variable_manager = ansible.vars.VariableManager()
    E   AttributeError: 'module' object has no attribute 'VariableManager'